spring:
  application:
    name: spring-2025
  cache:
    sisaIds: 3600000
  profiles:
    # This property is necessary to wire the default profile into the application
    active: @spring.profiles.active@
server:
  port: 8081
  servlet:
    # The context path is appended to the start of your path. With this, the path becomes "/api/..." rather than "/..."
    context-path: /api
